### ISSUE TITLE
Error when sometimes running simulation

### ISSUE THREAD

**Issue by AlbertG99** [jwohlwend/SimExm#1]
I get this error when running the simulation:
`cd examples; python run_sim.py; cd ..
Performing labeling simulation...
Performing expansion simulation...
Performing optics simulation...
Traceback (most recent call last):
  File "run_sim.py", line 148, in <module>
    sim_volume = optical_unit.resolve_volume(expanded_volume, expanded_dim, labeling_unit.get_fluors_used())
  File "SimExm/src/simulation/models/optics.pyx", line 112, in SimExm.src.simulation.models.optics.ConfocalUnit.resolve_volume (src/simulation/models/optics.c:4138)
  File "SimExm/src/simulation/models/optics.pyx", line 125, in SimExm.src.simulation.models.optics.ConfocalUnit.resolve_volume (src/simulation/models/optics.c:3937)
  File "SimExm/src/simulation/models/optics.pyx", line 174, in SimExm.src.simulation.models.optics.ConfocalUnit.resolve_channel (src/simulation/models/optics.c:5064)
  File "SimExm/src/simulation/models/optics.pyx", line 423, in SimExm.src.simulation.models.optics.ConfocalUnit.normalize (src/simulation/models/optics.c:9940)
ZeroDivisionError: float division
`

This error only occurs some of the time when I "make run" but not always. How do I fix this?

**Comment by jwohlwend** [comment]
Since the code is non-deterministic, there is a chance that if the labeling density is too low, no neurons gets labeled in one of the channels, resulting in a division by 0 at normalization time. Fixed it by adding an == 0 check in the commit: c14d7f6b0ed064ca613d31060fe62ffb85146db9
