### ISSUE TITLE
Dividing by 0 error still happening

### ISSUE THREAD

**Issue by AlbertG99** [jwohlwend/SimExm#2]
When I run the simulator, I am getting this error:
```
Traceback (most recent call last):
  File "run_sim.py", line 148, in <module>
    sim_volume = optical_unit.resolve_volume(expanded_volume, expanded_dim, labeling_unit.get_fluors_used())
  File "SimExm/src/simulation/models/optics.pyx", line 112, in SimExm.src.simulation.models.optics.ConfocalUnit.resolve_volume (src/simulation/models/optics.c:4138)
  File "SimExm/src/simulation/models/optics.pyx", line 125, in SimExm.src.simulation.models.optics.ConfocalUnit.resolve_volume (src/simulation/models/optics.c:3937)
  File "SimExm/src/simulation/models/optics.pyx", line 174, in SimExm.src.simulation.models.optics.ConfocalUnit.resolve_channel (src/simulation/models/optics.c:5064)
  File "SimExm/src/simulation/models/optics.pyx", line 423, in SimExm.src.simulation.models.optics.ConfocalUnit.normalize (src/simulation/models/optics.c:9940)
ZeroDivisionError: float division
```

What could be the issue?

**Comment by jwohlwend** [comment]
After you pulled, did you make sure to recompile the code with "make clean; make build" ? If you did not, the that would explain the problem. I am not able to replicate the error. My code runs fine even when no neurons get labeled. Could you try to replicate it again and give me the inputs that you used for the optical unit and the labeling unit ?

**Comment by jwohlwend** [comment]
Can I close this ?

**Comment by jwohlwend** [comment]
Confirmed fixed.
